In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4]
my_list = my_list * 2
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
# A numpy is superior
array = np.array([1, 2, 3, 4])
array = array * 2
print(array)

[2 4 6 8]


In [5]:
# Multi dimensional Array/Indexing
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])
print(array.shape)
print(array[0, 1, 0])

word = array[0, 0, 1] + array[1, 1, 2] + array[1, 1, 2]
print(word) 

(3, 3, 3)
D
BOO


## Slicing using Numpy

In [6]:
array = np.array([[1, 2, 3, 4], 
[4, 6, 7, 8], 
[9, 10, 11, 12], 
[13, 14, 15, 16]])

# array[start:end:step]
print(array[0])

[1 2 3 4]


In [9]:
print(array[1: 4])

[[ 4  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
# Step
array[0: 4: 2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [11]:
array[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [12]:
array[::-2]

array([[13, 14, 15, 16],
       [ 4,  6,  7,  8]])

### Column Selection

In [14]:
array

array([[ 1,  2,  3,  4],
       [ 4,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
array[:, 1]

array([ 2,  6, 10, 14])

In [17]:
array[:, 1: 4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [20]:
array[:, ::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  4],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [21]:
array

array([[ 1,  2,  3,  4],
       [ 4,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
array[0: 3, 0: 2]

array([[ 1,  2],
       [ 4,  6],
       [ 9, 10]])

In [31]:
array[0: 2, 2:]

array([[3, 4],
       [7, 8]])

In [32]:
array[2:, 0: 2]

array([[ 9, 10],
       [13, 14]])

In [33]:
array[2:, 2:]

array([[11, 12],
       [15, 16]])