In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4]
my_list = my_list * 2
print(my_list)

[1, 2, 3, 4, 1, 2, 3, 4]


In [3]:
# A numpy is superior
array = np.array([1, 2, 3, 4])
array = array * 2
print(array)

[2 4 6 8]


In [4]:
# Multi dimensional Array/Indexing
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']]])
print(array.shape)
print(array[0, 1, 0])

word = array[0, 0, 1] + array[1, 1, 2] + array[1, 1, 2]
print(word) 

(3, 3, 3)
D
BOO


## Slicing using Numpy

In [5]:
array = np.array([[1, 2, 3, 4], 
[4, 6, 7, 8], 
[9, 10, 11, 12], 
[13, 14, 15, 16]])

# array[start:end:step]
print(array[0])

[1 2 3 4]


In [6]:
print(array[1: 4])

[[ 4  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
# Step
array[0: 4: 2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [8]:
array[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [9]:
array[::-2]

array([[13, 14, 15, 16],
       [ 4,  6,  7,  8]])

### Column Selection

In [10]:
array

array([[ 1,  2,  3,  4],
       [ 4,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
array[:, 1]

array([ 2,  6, 10, 14])

In [12]:
array[:, 1: 4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [13]:
array[:, ::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  4],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [14]:
array

array([[ 1,  2,  3,  4],
       [ 4,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
array[0: 3, 0: 2]

array([[ 1,  2],
       [ 4,  6],
       [ 9, 10]])

In [16]:
array[0: 2, 2:]

array([[3, 4],
       [7, 8]])

In [17]:
array[2:, 0: 2]

array([[ 9, 10],
       [13, 14]])

In [18]:
array[2:, 2:]

array([[11, 12],
       [15, 16]])

## Arithmeric

### Scaler Arithmetic

In [19]:
array = np.array([1, 2, 3])
print(array + 1)

[2 3 4]


In [20]:
array - 2

array([-1,  0,  1])

In [21]:
array * 3

array([3, 6, 9])

In [ ]:
array / 4

array([0.25, 0.5 , 0.75])

In [23]:
array ** 5

array([  1,  32, 243])

### Vector Arithmentic Functions

In [27]:
array = np.sqrt(array)
array

array([1.        , 1.18920712, 1.31607401])

In [29]:
array = np.array([1.01, 2.5, 3.99])
np.round(array)

array([1., 2., 4.])

In [31]:
np.floor(array)

array([1., 2., 3.])

In [32]:
np.ceil(array)

array([2., 3., 4.])

In [33]:
np.pi

3.141592653589793

## EXERCISE

In [34]:
radii = np.array([1, 2, 3])
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


## Element-wise Arithmetic

In [35]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

In [37]:
array1 + array2

array([5, 7, 9])

In [38]:
array1 - array2

array([-3, -3, -3])

In [39]:
array1 * array2

array([ 4, 10, 18])

In [40]:
array1 / array2

array([0.25, 0.4 , 0.5 ])

In [41]:
array1 ** array2

array([  1,  32, 729])

## Comparison Operators

In [42]:
scores = np.array([91, 55, 100, 73, 82, 64])
scores == 100

array([False, False,  True, False, False, False])

In [43]:
scores >= 60

array([ True, False,  True,  True,  True,  True])

In [44]:
scores < 60

array([False,  True, False, False, False, False])

In [47]:
scores[scores < 60] = 0
scores

array([ 91,   0, 100,  73,  82,  64])

## Broadcasting

Broadcasting allows Numpy to perform operations on arrays with different shapes by virtually expanding dimensions so they match the larger array's shape

The dimensions have the same size
OR
One of the dimensions has the size of 1

In [49]:
array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1], [2], [3], [4]])
array1.shape, array2.shape

((1, 4), (4, 1))

In [50]:
array1 * array2

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [57]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
array2 = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
array1.shape, array2.shape

((4, 4), (4, 2))

In [58]:
array1 * array2

ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

## EXERCISE

In [60]:
array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
array1.shape, array2.shape

((1, 10), (10, 1))

In [61]:
array1 * array2

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

## Aggregate Functions
They summarize data and typically return a single value

In [62]:
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
np.sum(array)

np.int64(55)

In [64]:
np.mean(array)

np.float64(5.5)

In [65]:
np.std(array)

np.float64(2.8722813232690143)

In [66]:
np.var(array)

np.float64(8.25)

In [67]:
np.min(array)

np.int64(1)

In [68]:
np.max(array)

np.int64(10)

In [69]:
np.argmin(array)

np.int64(0)

In [70]:
np.argmax(array)

np.int64(9)

In [71]:
# Sum all columns
np.sum(array, axis = 0)

array([ 7,  9, 11, 13, 15])

In [ ]:
# Sum all rows
np.sum(array, axis = 1)

array([15, 40])

## Filtering
It includes the process of selecting the elements from an array that matches the given conditions

In [74]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])
teenagers = ages[ages < 18]
teenagers

array([17, 16, 15])

In [78]:
ages

array([[21, 17, 19, 20, 16, 30, 18, 65],
       [39, 22, 15, 99, 18, 19, 20, 21]])

In [80]:
adults = ages[(ages >= 18) & (ages < 65)]
adults

array([21, 19, 20, 30, 18, 39, 22, 18, 19, 20, 21])

In [81]:
seniors = ages[ages >= 65]
seniors

array([65, 99])

In [82]:
even = ages[ages % 2 == 0]
even

array([20, 16, 30, 18, 22, 18, 20])

In [84]:
odd = ages[ages % 2 == 1]
odd

array([21, 17, 19, 65, 39, 15, 99, 19, 21])

Every new array created from the original array has its shape changed to 1d array
If we need to preserve the original shape of the new array to be the same as the original array, we can use **where** functions

In [86]:
adults = np.where(ages >= 18, ages, -1)
adults

array([[21, -1, 19, 20, -1, 30, 18, 65],
       [39, 22, -1, 99, 18, 19, 20, 21]])