In [1]:
import numpy as np
import sys
import time

In [2]:
# Createing numpy/n-d arrays
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.zeros((3, 6))
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
arr4 = np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
arr6 = np.arange(2, 8, 2)
arr6

array([2, 4, 6])

In [7]:
arr7 = np.linspace(1, 10, 5)
arr7

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
arr8 = arr7.copy()
arr8

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Properties and Attributes

In [9]:
# Properties, Dimensions
arr1.shape

(3,)

In [10]:
arr4.shape

(5, 5)

In [11]:
arr4.ndim

2

In [12]:
arr9 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
arr9.ndim

3

In [13]:
arr9.shape

(3, 2, 2)

In [14]:
# Number of Items
arr9.size

12

In [15]:
arr9.itemsize

8

In [16]:
arr9.dtype

dtype('int64')

In [17]:
arr8.dtype

dtype('float64')

In [18]:
arr9.astype('float32').dtype

dtype('float32')

In [19]:
arr9.dtype

dtype('int64')

In [20]:
lista = range(100)
arr11 = np.arange(100)

In [21]:
print(sys.getsizeof(87) * len(lista))
print(arr11.itemsize * arr11.size)

2800
800


In [24]:
x = range(10000000)
y = range(10000000, 20000000)
start_time = time.time()

z = [x + y for x, y in zip(x, y)]

end_time = time.time()
print(end_time - start_time, "seconds")

3.2000741958618164 seconds


In [ ]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start_time = time.time()
c = a + b

end_time = time.time()
print(end_time - start_time, "seconds")

[10000000 10000002 10000004 ... 29999994 29999996 29999998]
0.06844210624694824 seconds


## Indexing, Slicing and Iteration

In [25]:
arr12 = np.arange(24).reshape(6, 4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
arr12[2]

array([ 8,  9, 10, 11])

In [30]:
arr12[2:3]

array([[ 8,  9, 10, 11]])

In [46]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [47]:
arr12[4:,2:6]

array([[18, 19],
       [22, 23]])

In [48]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [50]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
